name: JamesOppiabot

description: Handles user interactions with issues.
branding:
  color: purple
  icon: activity

inputs:
  repo-token: # Repository token.
    description: "The repository token needed to create comments."
    required: true
  google-api-key:
    description: "API key to access google APIs."
    required: true
  cla-sheet-id:
    description: "ID for the CLA spreadsheet."
    required: true

runs:
  using: "node12"
  main: "dist/index.js"
